cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: admin
      password: $2b$12$ICfCes9yGsqMmay22ip/uOISPlxQOBjJ17bVTnNXYCnkTOxP3/.u2
    carlos:
      email: hudsonmonteiro2012@gmail.com
      failed_login_attempts: 0
      first_name: Carlos
      last_name: Rolemberg
      logged_in: false
      password: $2b$12$Q/ZxQUDtzTi2/IDCLFucVO8OtBXDRd2hE0deWmPqxO0pgpmUMyqs.
      password_hint: Meu nome
      roles: null
    enzo:
      email: enzo@gmaill.com
      failed_login_attempts: 0
      logged_in: false
      name: enzo
      password: $2b$12$nP3XPGXWMr7Yy.XJNKrb2ORbApLkPsa6wJBLp.ITs0wK20nCg6VLu
    hudson:
      email: hudson@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Hudson
      password: $2b$12$dBk/yQIpDuTnorVzyGlrTOdbFOfV1CaRHMoHhay2vdgM4U1VNoPHq
    lucyo:
      email: hudsonmonteiro2013@gmail.com
      failed_login_attempts: 0
      first_name: Lucyo
      last_name: Diniz
      logged_in: false
      password: $2b$12$PISIFgEhxn.Z21sV318LJOtnt2C/uOSGJ6CRYL18H0OSQeZ6GMP5q
      password_hint: Meu nome
      roles: null
    nero:
      email: nero@gmail.com
      failed_login_attempts: 0
      first_name: enzo
      last_name: davi
      logged_in: true
      password: $2b$12$uiG2pU0y9J.pnipSqdzhjemqa5UWsz1TCYIUY38gSUxq1cT59ss6.
      password_hint: nero
      roles: null
    raphael:
      email: hudsonmonteiro2011@gmail.com
      failed_login_attempts: 0
      first_name: Raphael
      last_name: Saraiva
      logged_in: false
      password: $2b$12$fPrU9yIwn6fRBAqWJwth9.prKZcY7vk5KwJHpoKWmwrS19sYuDEwu
      password_hint: Meu nome
      roles: null
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$lrL7pLqt0C0LAypDm5h.QOzv0NiaNLSIUE/8sF50oiwicDbTMP.UO
pre-authorized:
  emails:
  - melsby@gmail.com
